image: node:11.14.0

# cache:
#   paths:
#     - node_modules/

# default:
#   before_script:
#     - npm ci

stages:
  - build
  - test
  # - deploy

build:
  stage: build
  script:
    - rm package.lock.json yarn.lock
    - npm install
    - gatsby clean
    - npm run build

test:
  stage: test
  script:
    - npm run jest
#
# deploy-staging:
#   stage: deploy
#   script:
#     - npm run deploy-stage
#   only:
#     - develop

# deploy-production:
#   stage: deploy
#   script:
#     - npm run deploy-prod
#   only:
#     - master
